config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :messages
  get 'messages/index'
  root to: "messages#index"
  #  resources :users, [:index, :edit, :update]
  resources :users
  resources :user11s,only: [:index,:new,:create]
  resources :monthls,only: [:index,:new,:create]
end



# get 'photos', to: 'photos#index'

# root_path	GET	/	messages#index

# resources :users, only: [:edit, :update]

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/monthl.rb
class Monthl < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         has_one :user11
         has_one :monthl
         
end

app/models/user11.rb
class User11 < ApplicationRecord
  belongs_to :user


  validates :text, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
   before_action :configure_permitted_parameters, if: :devise_controller?

  private
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:user])
   end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def index
    @index = Monthl.all
    
  end
  
  def new
  end
  
end

app/controllers/monthls_controller.rb
class MonthlsController < ApplicationController


def index
  # @monthl = Monthl.select("hiduke").order("hiduke ASC")
  @monthl = Monthl.all.order("hiduke ASC")
end


def new
  @monthl = Monthl.new
 
end

def create
  Monthl.create(monthl_params)
  @monthl = Monthl.create(monthl_params)
  
end

private
def monthl_params
  params.require(:monthl).permit(:hourlywage,:time,:hiduke).merge(user_id: current_user.id)
end



end

app/controllers/user11s_controller.rb
class User11sController < ApplicationController
  def index
  end


  def new
    @user11 = User11.new
   
  end

  def create
    User11.create(user11_params)
   
  end

  private
  def user11_params
    params.require(:user11).permit(:day, :time, :hourlywage).merge(user_id: current_user.id)
  end



end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def edit
  end

  def update
    if current_user.update(user_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:user, :email)
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Kintai</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" type="text/css" href="http://yui.yahooapis.com/3.18.1/build/cssreset/cssreset-min.css">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/messages/ show.html.erb
<div class="top">
  <div class="side-ber">
    <%= render "side_bar" %>
  </div>

 <div class="main-ber">
   <%= render "main_ber"%>
  </div>
</div>

app/views/messages/_kojin.html.erb
<div class="top">

  <div class="side-ber">
    <div class="side-ber-header">
  <div class="kojin-header">  
     <div class="current-user ">
      <%= link_to current_user.user, edit_user_path(current_user) %>
     </div>
     <div class="logout">
      <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: 'btn'%>
     </div>
  </div>
</div>
<div class="user-header-center">
   <div class="months">
     
      <div class="month">
         <% bb = [1,2,3,4,5,6,7,8,9,10,11,12]%>
        <% bb.each do |item| %>
        <a href="#">
         <%=" #{item}月"%>
        </a>
       <% end %>
       <%= link_to "aaa", monthls_path(current_user.id)%>
        <%# <%= link_to "aaa", user11s_path(current_user.id)%> 
      </div>
  
      
          
   </div>
</div>
<div class="side-be-under">
</div>

  </div>


 <div class="main-ber">
  <div clas="main-ber-header">
  <div class="title">
    <h1 class="midasi">¥ 時給計算 ¥</h1>
    </div>

</div>

<div class="main-ber-cnter">
   <div class="tourokus">
     <div class="main-syou">
       <div class="days">
        <div class="tuki">
        右の欄から記入する月を選んで下さい
        </div>
      </div>
     </div>

      
      </div>
   
    </div>
</div>

<div class="main-ber-under">
</div>



 
</div>

app/views/messages/_main_ber.html.erb
<div clas="main-ber-header">
  <div class="title">
    <h1 class="midasi">¥ 時給計算 ¥</h1>
    </div>

</div>

<div class="main-ber-cnter">
   <div class="tourokus">
     <div class="login">
       <%# <a href="edit_user_path">・ログイン</a> %>
       <%= link_to "・ログイン", new_user_session_path %>
     </div>
     <div class="sinki">
     <%= link_to "・新規登録",  new_user_registration_path %>
    </div>
   
    </div>
</div>

<div class="main-ber-under">
</div>

app/views/messages/_side_bar.html.erb
<div class="side-ber-header">
  <div class="user-name">
  ・ユーザー名
  </div>
</div>
<div class="user-header-center">
   <div class="users">
      <div class="user1">
        <a href="#">kuma</a>
      </div>
      
      <div class="user2">
        <a href="#">osima</a>
      </div>

   </div>
</div>
<div class="side-be-under">
</div>

app/views/messages/index.html.erb
<div class="top">

<% if user_signed_in? %>
    <%= render 'kojin' %>
<% else %>
     <div class="side-ber">
    <%= render "side_bar" %>
  </div>


 <div class="main-ber">
   <%= render "main_ber"%>
  </div>

 <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: 'btn'%>
</div>
<% end %>
  
</div>

app/views/monthls/create.html.erb
<div class="contents row">
  <div class="success">
    <h3>投稿が完了しました。</h3>
    <a class="btn" href="/">投稿一覧へ戻る</a>
  </div>
      <%= "今日のお給料は#{@monthl.time * @monthl.hourlywage}円です"%>
</div>



<%# @monthlr = monthlr.order(updated_at: :desc).limit(1) %>
    <%# @monthlr = monthlr.last(1) %>

app/views/monthls/index.html.erb
<div class="top">

  <div class="side-ber">
     <div class="side-ber-header">
         <div class="user-name1">
         <%= link_to "一覧に戻る",  root_path %>
         </div>
      </div>
     <div class="user-header-center">
   <div class="users">
      <div class="user1">
        <% @monthl.each do |hiduke| %>
        <%= hiduke.hiduke %><br>
        <%= "今日のお給料は#{hiduke.time * hiduke.hourlywage}円です"%>
        <% end %>
        <%# <a href="#">1日の給料 4050円</a> %>
        
      </div>
      
      <%# <div class="user2">
        <a href="#">2日の給料 4050円</a>
      </div> %>
         
      </div>
      </div>
      <div class="side-be-under">
       </div>


  </div>






   <div class="main-ber">

     <div clas="main-ber-header">
      <div class="title">
       <h1 class="midasi">¥ 11月の時給計算 ¥</h1>
      </div>
    </div>
     
     <div class="main-ber-cnter">
      <div class="okyuryous">
     <div class="tourokus">
         <div class="touroku">
          <%= link_to "・登録画面・",  new_monthl_path %>
          </div>
     </div>
     <div class="ruikei">
     <div class="taimes"> 
      <%# <% @monthl.each do |hiduke| %>
        <%# <%= hiduke.time += hiduke.time%>
        <%# <% end %>  
        <%="今月の作業時間は#{Monthl.all.sum(:time)}時間です"%>
       
       <%# 今月の累計時間 66時間 %>

     </div>
     <div class="moneys">
       <%array = []%> 
        <%Monthl.all.each do |monthl|%>
         <%array << monthl.time * monthl.hourlywage%> 
         <%end%>
          <%="今月のお給料は#{array.sum}円です"%>

            
          

         
        <%# <%=array.sum%> 
    </div>
    </div>
   
    </div>
   </div>

   </div>
    
    <div class="main-ber-under">
    </div>

</div>

app/views/monthls/new.html.erb
<div class="contents row">
  <div class="container">
    <h3>本日の勤怠時間を入力して下さい</h3>
    <%= form_with(model: @monthl, local: true) do |form| %>
      <%= form.date_select :hiduke,{discard_year: true, use_month_numbers: true,  },  placeholder: "働いた日" %>
      <%= form.number_field :time, step: '0.25', placeholder: "働いた時間" %>
      <%= form.text_field :hourlywage, placeholder: "時給"%>
      <%= form.submit "SEND" %>
    <% end %>
  </div>
</div>

app/views/user11s/create.html.erb
<div class="contents row">
  <div class="success">
    <h3>投稿が完了しました。</h3>
    <a class="btn" href="/">投稿一覧へ戻る</a>
  </div>
</div>

app/views/user11s/index.html.erb
<div class="top">

  <div class="side-ber">
     <div class="side-ber-header">
         <div class="user-name1">
         <%= link_to "一覧に戻る",  root_path %>
         </div>
      </div>
     <div class="user-header-center">
   <div class="users">
      <div class="user1">
        <a href="#">1日の給料 4050円</a>
      </div>
      
      <div class="user2">
        <a href="#">2日の給料 4050円</a>
      </div>

      </div>
      </div>
      <div class="side-be-under">
       </div>


  </div>






   <div class="main-ber">

     <div clas="main-ber-header">
      <div class="title">
       <h1 class="midasi">¥ 11月の時給計算 ¥</h1>
      </div>
    </div>
     
     <div class="main-ber-cnter">
      <div class="okyuryous">
     <div class="tourokus">
         <div class="touroku">
          <%= link_to "・登録画面・",  new_user11_path %>
          </div>
     </div>
     <div class="ruikei">
     <div class="taimes">
       今月の累計時間 66時間
     </div>
     <div class="moneys">
       今月のお給料  72000円
    </div>
    </div>
   
    </div>
   </div>

   </div>
    
    <div class="main-ber-under">
    </div>

</div>

app/views/user11s/new.html.erb
<div class="contents row">
  <div class="container">
    <h3>本日の勤怠時間を入力して下さい</h3>
    <%= form_with(model: @user11, local: true) do |form| %>
      <%= form.date_select :day,{discard_year: true, use_month_numbers: true,  },  placeholder: "働いた日" %>
      <%= form.number_field :time, step: '0.25', placeholder: "働いた時間" %> 
      <%= form.text_field :hourlywage, placeholder: "時給"%>
      <%= form.submit "SEND" %>
    <% end %>
  </div>
</div>

app/views/users/edit.html.erb
<h2>アカウント編集</h2>

<%= form_with model: current_user, local: true do |f| %>
   <div class="field">
    <%= f.label :user %><br />
    <%= f.text_field :user %>
  </div>


<div>
<%names = ["Pirori","Okachan","Ida"]%>




  <div class="field">
    <%= f.label :email %><br />
    <%= f.email_field :email, autofocus: true, autocomplete: "email" %>
  </div>    
    <div class="actions">
    <%= f.submit "編集" %>
  </div>
<% end %>